// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKsYGW16nPSOKKsaOczLl-WQT8Wc1cyiE',
    appId: '1:404701850417:web:8a3d751304685b0864de10',
    messagingSenderId: '404701850417',
    projectId: 'itinereo-3f714',
    authDomain: 'itinereo-3f714.firebaseapp.com',
    storageBucket: 'itinereo-3f714.firebasestorage.app',
    measurementId: 'G-8EYERPPGV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5HhqeYt8nu4ju-RafzS0FlfnRzWb-8RE',
    appId: '1:404701850417:android:5bb7567ce78c9faf64de10',
    messagingSenderId: '404701850417',
    projectId: 'itinereo-3f714',
    storageBucket: 'itinereo-3f714.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUEASC1wGok2X2gZsxWZWqy1_UfuePwQc',
    appId: '1:404701850417:ios:34be3d6356c4373464de10',
    messagingSenderId: '404701850417',
    projectId: 'itinereo-3f714',
    storageBucket: 'itinereo-3f714.firebasestorage.app',
    iosBundleId: 'com.example.itinereo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUEASC1wGok2X2gZsxWZWqy1_UfuePwQc',
    appId: '1:404701850417:ios:34be3d6356c4373464de10',
    messagingSenderId: '404701850417',
    projectId: 'itinereo-3f714',
    storageBucket: 'itinereo-3f714.firebasestorage.app',
    iosBundleId: 'com.example.itinereo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKsYGW16nPSOKKsaOczLl-WQT8Wc1cyiE',
    appId: '1:404701850417:web:aa445e61a95560d764de10',
    messagingSenderId: '404701850417',
    projectId: 'itinereo-3f714',
    authDomain: 'itinereo-3f714.firebaseapp.com',
    storageBucket: 'itinereo-3f714.firebasestorage.app',
    measurementId: 'G-Z29VF9S2ZE',
  );

}